# Generated by Django 3.0.2 on 2020-01-19 06:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Score')),
            ],
            managers=[
                ('get_student', django.db.models.manager.Manager()),
            ],
        ),
    ]
